sonar.organization=brianegge
sonar.projectKey=brianegge_homeassistant-dial-a-story
sonar.sources=custom_components/dial_a_story
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.12
